# Generated by Django 4.2.6 on 2023-11-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0002_alter_blog_date_created_alter_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
