# Generated by Django 4.2.6 on 2023-11-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0005_remove_blog_images_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(to='community_web_application.image'),
        ),
    ]
