# Generated by Django 4.2.6 on 2023-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0007_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
