# Generated by Django 4.2.6 on 2023-11-13 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0008_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='phone_no',
        ),
    ]
