# Generated by Django 4.2.6 on 2023-11-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0009_remove_author_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
