# Generated by Django 4.2.6 on 2023-11-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0012_alter_author_options_alter_author_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
