# Generated by Django 4.2.6 on 2023-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0013_alter_author_options_alter_author_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
