# Generated by Django 4.2.6 on 2023-11-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0017_alter_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
