# Generated by Django 4.2.6 on 2023-11-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0018_alter_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
