# Generated by Django 4.2.6 on 2023-11-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0019_alter_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
    ]
