# Generated by Django 4.2.6 on 2023-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0026_social_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
