# Generated by Django 4.2.6 on 2023-11-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0027_alter_teammembers_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='urls',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community_web_application.social'),
        ),
    ]
