# Generated by Django 4.2.6 on 2023-11-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0028_remove_teammembers_urls_teammembers_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='urls',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='urls',
            field=models.ManyToManyField(to='community_web_application.social'),
        ),
    ]
