# Generated by Django 4.2.6 on 2023-12-21 06:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0029_remove_teammembers_urls_teammembers_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=50000),
        ),
    ]
