# Generated by Django 4.2.6 on 2024-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0030_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_image', models.ImageField(upload_to='stats_images/')),
                ('owner_name', models.CharField(max_length=50)),
                ('machine_type', models.TextField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Server', 'Server'), ('Other', 'Other')], default='Desktop')),
                ('description', models.TextField(max_length=500)),
                ('original_configuration', models.CharField(max_length=500)),
                ('new_configurations', models.CharField(max_length=500)),
            ],
        ),
    ]
