# Generated by Django 4.2.6 on 2024-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0031_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='new_configurations',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stats',
            name='original_configuration',
            field=models.TextField(max_length=500),
        ),
    ]
