# Generated by Django 4.2.6 on 2024-01-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_web_application', '0032_alter_stats_new_configurations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='new_configurations',
            new_name='new_configuration',
        ),
    ]
